# Library imports
import random

# The max number the computer will generate a random number to
max_number = 1000

# Print program title and description on how to play the game
print("High Low Game - By: Darian Benam")
print("--------------------------------\n")
print("This is a game where the computer generates a number from 1 to", max_number, "The goal of this game is to guess the number generated by the computer in the least amount of attempts.\n")
print("If your guess is to high, the program will tell you it's too high. If it's too low, the computer will tell you it's too low. If your guess is equal to the secret number, you win!")

# Generate a random number from 1 to the value of max_number
secret_number = random.randint(1, max_number)

# The amount of attempts the user has tried to guess the word
attempts = 0

# Main game loop
while True:
    try:
        # Get the guess of the user
        guess = int(input("\nEnter your guess: "))
    except ValueError as err:
        print("That is not an integer. Please try again.")
        continue

    # Add 1 to the total attempts
    attempts += 1

    if guess > secret_number: # Too high
        print("The number you inputted was too high! Please try again.")
    elif guess < secret_number: # Too low
        print("The number you inputted was too low! Please try again.")
    else: # Guess is equal to the secret_number
        break

print("Congratulations, you guess the number. It took you", attempts, "attempts to guess the word")